android/app/build.gradle, android/app/src/debug/res/values/strings.xml, android/build.gradle, ios/Podfile, ios/Podfile.lock, ios/students.xcodeproj/project.pbxproj, ios/students.xcodeproj/xcshareddata/xcschemes/students dev.xcscheme, ios/students/DevInfo.plist, package-lock.json, package.json, src/core/contexts/PreferencesContext.ts, src/core/queries/courseHooks.ts, src/features/agenda/components/WeeklyAgenda.tsx, src/features/agenda/queries/agendaHooks.ts, src/features/services/components/ServicesNavigator.tsx, src/features/services/screens/ServicesScreen.tsx
=>  chore: allow parallel installation of App store and development versions

ios/Podfile.lock, package-lock.json, package.json, src/core/providers/UiProvider.tsx
=> fix(ui): override native theme based on user preferences

assets/translations/en.json, assets/translations/it.json, src/features/services/components/ChatMessage.tsx, src/features/services/components/TicketStatusInfo.tsx
=> fix(tickets): insert agent id in ticket answer

assets/translations/it.json, lib/ui/components/ScreenContainer.tsx, src/features/services/screens/CreateTicketScreen.tsx
=> fix(tickets): avoid text area being hidden by the keyboard in ticket creation

src/core/components/VideoPlayer.ios.tsx
=> fix(courses): video player on iOS does not play audio when the device is in silent mode

assets/translations/en.json, assets/translations/it.json, lib/ui/components/CtaButton.tsx, lib/ui/components/ListItem.tsx, lib/ui/components/RadioGroup.tsx, lib/ui/types/Input.ts, package-lock.json, src/core/components/EventDetails.tsx, src/core/queries/examHooks.ts, src/core/themes/dark.ts, src/core/themes/light.ts, src/core/types/api.ts, src/features/teaching/components/ExamCTA.tsx, src/features/teaching/components/ExamListItem.tsx, src/features/teaching/components/ExamStatusBadge.tsx, src/features/teaching/components/TeachingNavigator.tsx, src/features/teaching/screens/ExamQuestionScreen.tsx, src/features/teaching/screens/ExamRequestScreen.tsx, src/features/teaching/screens/ExamScreen.tsx, src/features/teaching/screens/ExamsScreen.tsx, src/utils/dates.ts
- Add status badge - Closes #114
- Allow to book exam with question - Closes #198
- Allow to book a requestable exam - Closes #199
=> refactor(exams): improve UI

assets/translations/en.json, assets/translations/it.json, package-lock.json, src/core/components/RootNavigator.tsx, src/core/contexts/PreferencesContext.ts, src/core/providers/PreferencesProvider.tsx, src/core/providers/UiProvider.tsx, src/core/queries/studentHooks.ts, src/core/screens/LoginScreen.tsx, src/features/user/screens/SettingsScreen.tsx
=> fix: handle language preference forwarding to the server

assets/translations/en.json, assets/translations/it.json, lib/ui/components/CtaButton.tsx, lib/ui/components/Snackbar.tsx, lib/ui/types/Feedback.ts, package-lock.json, package.json, src/App.tsx, src/config/api.tsx, src/core/contexts/FeedbackContext.ts, src/core/providers/FeedbackProvider.tsx, src/core/queries/courseHooks.ts, src/core/screens/LoginScreen.tsx, src/features/agenda/screens/BookingScreen.tsx, src/features/teaching/components/ExamCTA.tsx, src/features/teaching/components/TeachingNavigator.tsx, src/features/teaching/screens/CourseAssignmentPdfCreationScreen.tsx, src/features/teaching/screens/CourseAssignmentUploadConfirmationScreen.tsx, src/features/teaching/screens/CourseAssignmentUploadScreen.tsx, src/features/teaching/screens/CourseAssignmentsScreen.tsx, src/features/teaching/screens/CoursePreferencesScreen.tsx, src/features/teaching/screens/ExamQuestionScreen.tsx, src/features/teaching/screens/ExamRequestScreen.tsx, src/features/teaching/screens/ExamScreen.tsx, src/features/teaching/types/Assignment.ts, src/features/user/screens/SettingsScreen.tsx
Closes #243, closes #171, closes #69
=> feat(ui): create platform-agnostic Snackbar

src/core/screens/LoginScreen.tsx
=> fix(auth): fix forgot password link

src/core/providers/UiProvider.tsx, src/features/user/screens/SettingsScreen.tsx
=> fix(ui): fix app system theme

src/features/teaching/screens/NoticeScreen.tsx
=> chore(courses): make text URLs included in course notices clickable

src/features/teaching/components/CourseNavigator.tsx
=> fix(courses): improve space usage in course header

src/core/hooks/usePushNotifications.ts, src/features/teaching/screens/CourseFilesScreen.tsx, src/features/teaching/screens/CourseNoticesScreen.tsx
=> fix(courses): prevent unnecessary rerenders when in CourseNoticesScreen

src/core/components/HtmlView.tsx
=> fix(courses): notices render badly when teachers include custom styles

src/features/agenda/components/ExamCard.tsx, src/features/teaching/screens/ExamScreen.tsx
=> fix(agenda): manage multiple rooms in agenda exam card

src/core/queries/courseHooks.ts, src/features/courses/screens/CourseLecturesScreen.tsx, src/features/courses/types/CourseLectureSections.ts
=> fix(courses): cannot see previous years virtual classrooms

src/core/contexts/PreferencesContext.ts, src/core/providers/PreferencesProvider.tsx, src/features/agenda/components/AgendaNavigator.tsx, src/features/agenda/components/AgendaTypeFilter.tsx, src/features/agenda/queries/agendaHooks.ts, src/features/agenda/screens/AgendaScreen.tsx, src/features/agenda/screens/AgendaWeekScreen.tsx
=> fix(agenda): mantain agenda screen layout orientation

assets/translations/en.json, assets/translations/it.json, src/features/user/screens/SettingsScreen.tsx
=> chore: show the app version

src/core/components/TextWithLinks.tsx, src/features/tickets/components/TextMessage.tsx, src/utils/html.ts
=> fix(tickets): add clickable links

src/features/tickets/screens/CreateTicketScreen.tsx
=> fix(tickets): eol is not respected in writing a new ticket

src/core/queries/studentHooks.ts, src/features/agenda/queries/agendaHooks.ts, src/features/agenda/queries/lectureHooks.ts, src/features/agenda/screens/AgendaScreen.tsx, src/features/agenda/screens/AgendaWeekScreen.tsx, src/features/courses/components/CourseListItem.tsx, src/features/courses/screens/CoursePreferencesScreen.tsx, src/features/places/hooks/useSearchPlaces.ts
=> refactor(agenda): change state management from infinite queries to standard ones

src/utils/html.ts
=> fix: prevent url linking when already wrapped into an anchor tag

lib/ui/utils/calendar.ts
=> fix: adjust view for 7-day calendar in calendar.tsx

package-lock.json, package.json, src/core/queries/offeringHooks.ts, src/features/offering/navigation/DegreeTopTabsNavigator.tsx, src/features/offering/types/Degree.ts
=> fix(offering): fix offering year formatting, add filter state

src/core/components/RootNavigator.tsx, src/core/hooks/useHideTabs.ts, src/core/hooks/usePushNotifications.ts, src/core/queries/studentHooks.ts, src/core/screens/OnboardingModal.tsx
=> fix: messages dialog does not always open when receiving a message notification

src/core/queries/authHooks.ts
=> fix: remove user queries without invalidating on logout

assets/translations/en.json, assets/translations/it.json, ios/Podfile.lock, package-lock.json, package.json, src/features/agenda/components/AgendaNavigator.tsx, src/features/agenda/components/WeeklyAgenda.tsx, src/features/agenda/screens/AgendaScreen.tsx, src/features/agenda/screens/AgendaWeekScreen.tsx, src/features/agenda/types/AgendaOption.ts, src/features/agenda/types/AgendaState.ts
=> fix(agenda): navigate to date

src/core/hooks/messaging.ts
=> fix(notifications): explicitly ask for permission on Android if not implicitly granted

package-lock.json, package.json, src/core/queries/examHooks.ts, src/features/teaching/components/ExamCTA.tsx, src/features/teaching/screens/ExamQuestionScreen.tsx, src/features/teaching/screens/ExamRequestScreen.tsx
Requires API modification to be tested
Closes #409
Closes #410
=> fix(exams): allow to book exams for courses divided in modules

src/features/courses/screens/CourseInfoScreen.tsx, src/features/teaching/screens/ExamsScreen.tsx, src/features/teaching/screens/TeachingScreen.tsx
=> fix(exams): make ExamListItem key unique

src/features/agenda/queries/agendaHooks.ts, src/features/agenda/screens/AgendaScreen.tsx, src/features/agenda/screens/AgendaWeekScreen.tsx, src/features/agenda/screens/BookingScreen.tsx, src/features/bookings/components/BookingListItem.tsx, src/features/bookings/components/BookingSlotModal.tsx, src/features/bookings/screens/BookingSeatScreen.tsx, src/features/bookings/screens/BookingSlotScreen.tsx, src/features/courses/screens/CourseNoticesScreen.tsx, src/features/tickets/components/MessageTime.tsx, src/utils/dates.ts
=> fix: keep Europe/Rome timezone when displaying dates

package-lock.json, package.json, src/core/queries/webMailHooks.ts, src/features/services/screens/ServicesScreen.tsx
=> feat: webmail added

lib/ui/components/AgendaCard.tsx, lib/ui/components/calendar/CalendarBody.tsx, lib/ui/components/calendar/CalendarEvent.tsx, lib/ui/types/Calendar.ts, lib/ui/utils/calendar.ts
=> fix(agenda): fix tablet agenda view

assets/translations/en.json, assets/translations/it.json, package-lock.json, package.json, src/features/courses/screens/CourseInfoScreen.tsx
=> feat(courses): add external links in course info tab

src/features/tickets/components/MessagingView.tsx
=> fix(tickets): fix ticket reply sent multiple times

assets/translations/en.json, assets/translations/it.json, lib/ui/components/CtaButton.tsx, lib/ui/components/ErrorCard.tsx, lib/ui/types/Theme.ts, package-lock.json, package.json, src/core/themes/dark.ts, src/core/themes/light.ts, src/features/teaching/components/ExamCTA.tsx, src/features/teaching/screens/ExamScreen.tsx, src/features/teaching/utils/exam.ts
=> fix(exams): provide a feedback when an exam cannot be booked, Ref #495

src/features/teaching/screens/TeachingScreen.tsx
=> fix(exams): sort exams by date in the TeachingScreen.tsx, Ref #504

src/features/courses/screens/CourseDirectoryScreen.tsx
=> fix(courses): prioritize sorting by date, if they are the same sort by name in increasing order

src/core/components/AppContent.tsx, src/core/hooks/messaging.ts, src/core/queries/authHooks.ts
=> Fix fcm token update onto patchClient

src/features/user/screens/NotificationsScreen.tsx
Remove courses notifications in settings
=> fix(notifications): remove courses notifications

src/utils/bookings.ts
fix(booking): fix booking seat selection special needs in current range of time
=> fix(booking): fix booking seat selection special needs

src/core/hooks/useNotifications.ts, src/core/queries/courseHooks.ts, src/features/courses/components/CourseListItem.tsx, src/features/courses/navigation/CourseNavigator.tsx, src/features/courses/navigation/CourseSharedScreens.tsx, src/features/courses/screens/CourseInfoScreen.tsx, src/features/teaching/screens/TeachingScreen.tsx
=> fix(courses): enable notifications from courses in previous years

lib/ui/components/calendar/CalendarEvent.tsx, lib/ui/hooks/calendar/useCalendarTouchableOpacityProps.ts, lib/ui/types/Calendar.ts, src/features/agenda/screens/AgendaWeekScreen.tsx, src/features/bookings/screens/BookingSlotScreen.tsx, src/utils/bookings.ts
fix console error when enter in agenda/booking and fix crash when in booking have one topic without subtopic in first position
=> fix(bookings): fix console error and crash when enter in agenda/booking

src/features/agenda/components/WeekFilter.tsx
=> fix(agenda): update week filter to show dates from Monday to Sunday

src/core/components/VideoPlayer.android.tsx
=> fix(courses): pause video when user navigates away from tab

assets/translations/en.json, assets/translations/it.json, lib/ui/components/ScreenDateTime.tsx, src/core/queries/examHooks.ts, src/features/teaching/components/ExamListItem.tsx, src/features/teaching/screens/ExamScreen.tsx, src/utils/dates.ts
=> fix(exams): when an exam has the null examStartsAt field, no exams were displayed

assets/translations/en.json, assets/translations/it.json, lib/ui/types/Theme.ts, src/core/components/ReadMoreText.tsx, src/core/themes/dark.ts, src/core/themes/light.ts, src/features/transcript/components/TeacherMessage.tsx, src/features/transcript/screens/ProvisionalGradeScreen.tsx
=> feat(exams): show the message from professor when is available

assets/translations/en.json, assets/translations/it.json, ios/Podfile.lock, lib/ui/components/CtaButton.tsx, src/core/screens/LoginScreen.tsx, src/features/agenda/screens/BookingScreen.tsx, src/features/agenda/screens/LectureScreen.tsx, src/features/places/components/PlacesNavigator.tsx, src/features/places/screens/PlaceScreen.tsx
=> feat(booking): add poi when have only coordinates + add description field to lecture details

src/features/agenda/components/AgendaTypeFilter.tsx, src/features/agenda/screens/AgendaWeekScreen.tsx
=> feat(agenda): changed agenda filter

assets/translations/en.json, assets/translations/it.json, package-lock.json, package.json, src/core/queries/webMailHooks.ts, src/features/agenda/screens/BookingScreen.tsx, src/features/agenda/screens/DeadlineScreen.tsx, src/features/courses/screens/CourseInfoScreen.tsx, src/features/people/screens/PersonScreen.tsx, src/features/services/components/ServicesNavigator.tsx, src/features/services/screens/JobOfferScreen.tsx, src/features/services/screens/NewsItemScreen.tsx, src/features/services/screens/ServicesScreen.tsx, src/features/services/screens/WebView.tsx, src/features/surveys/components/SurveyListItem.tsx, src/features/surveys/components/SurveyListItemByTypeName.tsx, src/shared/navigation/SharedScreens.tsx
=> feat(webview): add webview component for web mail

src/features/places/components/PlacesBottomSheet.tsx, src/features/places/screens/BuildingScreen.tsx
fix POI when click a building from bottomsheet
closes #630
=> fix(places): fix search building from bottomsheet

.gitignore, android/app/build.gradle, android/app/src/main/java/it/polito/students/MainActivity.kt, android/app/src/main/java/it/polito/students/MainApplication.kt, android/settings.gradle, babel.config.js, ios/Podfile, ios/Podfile.lock, ios/students.xcodeproj/project.pbxproj, ios/students/AppDelegate.h, ios/students/AppDelegate.mm, metro.config.js, package-lock.json, package.json, src/core/hooks/useOpenInAppLink.ts, src/core/queries/webMailHooks.ts, src/core/themes/dark.ts, src/features/agenda/screens/BookingScreen.tsx, src/features/agenda/screens/DeadlineScreen.tsx, src/features/courses/screens/CourseInfoScreen.tsx, src/features/people/screens/PersonScreen.tsx, src/features/services/screens/JobOfferScreen.tsx, src/features/services/screens/NewsItemScreen.tsx, src/features/services/screens/ServicesScreen.tsx, src/features/surveys/components/SurveyListItem.tsx, src/features/surveys/components/SurveyListItemByTypeName.tsx
=> feat(webview): add expo web-browser for open webmail, and all the links

assets/translations/en.json, assets/translations/it.json, lib/ui/components/CtaButton.tsx, src/features/transcript/components/ProvisionalGradeListItem.tsx, src/features/transcript/screens/ProvisionalGradeScreen.tsx
=> fix(transcript): make the rejection date have the same style as the button

src/features/places/screens/PlacesScreen.tsx
=> fix(places): reset selected floor when change campus

src/features/offering/navigation/DegreeTopTabsNavigator.tsx
=> fix(offering): display correct year in offering
